### ISSUE TITLE
SQL Map?

### ISSUE THREAD

**Issue by TrollWarlord** [lukevers/kittens#63]
How do you start the SQL server? I don't want to make records by hand.. no setup?

**Comment by lukevers** [comment]
You don't have to. It sets it up itself if there's nothing setup already. I'm using [gorm](github.com/jinzhu/gorm) as an ORM library and using the `AutoMigrate` func to set it up.

**Comment by Term1nal** [comment]
Close?

**Comment by lukevers** [comment]
I was going to leave it open in case for some reason there really was something wrong--I thought commenting would be enough for @TrollWarlord to try it out and see if it worked, but yeah--after 6 months it's probably safe to close this.
