### ISSUE TITLE
undefined: tls.DialWithDialer

### ISSUE THREAD

**Issue by bateau84** [lukevers/kittens#64]
trying to create a docker image. get this error on build:

github.com/fluffle/goirc/client
../github.com/fluffle/goirc/client/connection.go:246: undefined: tls.DialWithDialer

**Comment by Term1nal** [comment]
It appears to me that you may have an old version of Go. As far as I am aware, tls.DialWithDialer is only available in go >= 1.3

**Comment by Term1nal** [comment]
#66 removes versions before 1.3 from travis

**Comment by lukevers** [comment]
Thanks, @Term1nal! It's probably safe to close this then. If you're still having problems after upgrading go, @bateau84, feel free to open this back up!
