### ISSUE TITLE
New setup doesn't set up database (database.go:101 using unaddressable value)

### ISSUE THREAD

**Issue by michaelowens** [lukevers/kittens#65]
I'm new to the Go language and scene, so I may have forgotten something, but I can't seem to find what it is. I followed the README, but I can't login to the interface, but I think it doesn't make the database properly. It creates the sqlite kittens.db file (and I have sqlite3 installed), but it errors on boot:

`database.go:101 using unaddressable value`

![error](http://i.imgur.com/ZHt1FPA.png)

go version go1.4.2 darwin/amd64

Did I forget a step? I also tried re-building several times which didn't solve it. I tried disabling the line, which did get rid of the warnings (so it does build properly).

**Comment by michaelowens** [comment]
After some googling and looking at the GORM documentation, changing line 101 to the following worked for me:

`db.AutoMigrate(&User{}, &Server{}, &Channel{}, &IrcUser{}, &IrcUserChannel{})`

**Comment by lukevers** [comment]
Hey thanks for letting me know. I haven't had time to work on this in a while and I know gorm has progressed a lot since I used it with this. I'll both update that soon and try to work on it more.
